model:
  base_model_id: meta-llama/Llama-2-7b-chat-hf
  lora_path: path/to/lora/adapters
quantization:
  bnb_4bit_compute_dtype: float16
  bnb_4bit_quant_type: nf4
  bnb_4bit_use_double_quant: false
  load_in_4bit: true
